name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Install rubocop
      run: gem install rubocop
    - name: Execute rubocop
      run: rubocop
